name: Coverage

on:
  workflow_call:
    inputs:
      test:
        required: false
        type: string
        default: vp test run --coverage

      build:
        required: false
        type: string
        default: vp run build

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Setup Vite Plus
        uses: sxzz/workflows/setup-vp@main

      - name: Build
        run: ${{ inputs.build }}

      - name: Coverage
        run: ${{ inputs.test }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          use_oidc: true
